application: gaesite1623
version: 1
runtime: python
api_version: 1

handlers:  
- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/(.*)

- url: /css/(.*)
  static_files: static/css/\1
  upload: static/css/(.*)

- url: /js/(.*)
  static_files: static/js/\1
  upload: static/js/(.*)
 
- url: /index.pp
  script: index.py

- url: /admin.pp
  script: admin.py

- url: /home.pp
  script: home.py

- url: /.*
  script: not_found.py

